### ISSUE TITLE
reponsive on iphone / android browser

### ISSUE THREAD

**Issue by robbee** [twigy/twigy-web#11]
Yo 

J'arrive pas a comprendre pourquoi ? mais le responsive de fonctionne pas complement sur mobile lorsque l'ecran est petit (iphone 6 en mode portait par exemple) alors qu'il fonctionne dans l'emulateur chrome ou quand je met l'iphone en paysage

L'image du helper est retourné a la ligne (cf copy d'écran) 

Merci

![img_3018](https://cloud.githubusercontent.com/assets/5807275/15044811/49552cea-12d7-11e6-884f-18ba0ff6ea63.PNG)

**Comment by alaumiere** [comment]
Hello,
ça devrait être ok.
Pour les petits écran l'avatar sera légèrement plus petit et en bonus l'affichage des périodes est désactivé.
A+

**Comment by robbee** [comment]
J'ai pas pu testé encore mais ca devrait etre ok !! Parfait merci !
