### ISSUE TITLE
images assets 

### ISSUE THREAD

**Issue by robbee** [twigy/twigy-web#12]
Yo

Je n'arrive pas a brancher les images.. Je galere :-( 

`http://twigy.herokuapp.com/css/getHelpersCSSByHelpedId/?helpedId=1` 
- renvoie : `.usr-5{background-image:url(/assets/people/Martine-square.png);}.usr-4{background-image:url(/assets/people/Aurelien-square.png);}.usr-3{background-image:url(/assets/people/Jean-square.png);}.usr-2{background-image:url(/assets/people/Claire-square.png);}.usr-1{background-image:url(/assets/people/Alex-square.png);}`

`http://twigy.herokuapp.com/assets/people/Martine-square.png``
- renvoie bien l'image

Y a qqchose qui m'échappe ... Grrr !

**Comment by alaumiere** [comment]
Le content-type de la response délivrée par le back devrait être text/css et non html.

**Comment by robbee** [comment]
Ha bah oui ... effectivement, ca va beaucoup mieux comme ca ;-)

Merci !!!
