### ISSUE TITLE
"loading animation"

### ISSUE THREAD

**Issue by robbee** [twigy/twigy-web#13]
Salut Aurelien

Super les filters :-) hyper pratique !

Sinon, juste une petite info que tu auras remarqué :-) En passant a rails.. j'ai cassé la feature "optimisitic assignement" que tu avais fait.. :-( Je suis navré. L'objet twig que renvoie maintenant le backend est plus complet (il y a notamment les helper/helped/comment/reccource...etc)  Bref ..

Du coup je me pose la question entre ca (comportement optimiste) et une "loading animation" comme tu l'avait fait également sur la création (que je trouve plutôt sympa aussi)

On pourrait généraliser la loading animation ? pour l'instant tout au moins ! Qu'est ce t'en penses ?

++ Alex

**Comment by alaumiere** [comment]
Hi,

De quoi parle tu concernant la "loading animation" ? Est-ce la notification toastr ? Sinon je ne me rappelle pas avoir mis d'animation.
Pour le comportement optimiste sur l'assignment, pour le remettre en place il suffit de répercuter la modif de structure dans les méthodes du controller (c'est à dire utiliser `twig.extended_properties.shared.helper.id` à la place de `twig.helperId`).

Effectivement le backend renvoi dorénavant les twigs en peuplant l'objet helper pour chaque twig. Je pense que cela alourdit la réponse HTTP inutilement, seul la référence vers l'id du helper est vraiment nécessaire. Qui plus est, chaque helper peux avoir l'avatar sous forme de data_uri ... donc potentiellement plusieurs dizaines de Ko pour chaque helper de chaque twig. Idem pour le password hash, le front n'a pas vraiment besoin de cette info (en plus niveau sécu c'est mal).
Bref, peupler autant la réponse ce n'est pas forcément une bonne idée à mon avis.

Pour en revenir au sujet, je trouve que le comportement optimiste c'est un plus au niveau de l'UX, d'ailleurs de plus en plus de monde l'applique, facebook quand tu ajoute un post, gmail quand tu supprime un mail...
Si il y a quelque chose à généraliser c'est ce comportement, ajouter une animation en plus sur ce comportement ça serait top, mais faut trouver l'animation appropriée pour chaque comportement. 

A+

**Comment by robbee** [comment]
Yo ! Désolé pour la réponse tardive

Oui je parlais de l'animation du toastr et ok pour le comportement optimiste, je vais regarder pour le remettre en place.

Ok pour la taille de la réponse .. elle pourrait etre optimisé un peu plus je suis d'accord.. (idem pour le pwd :-/)

Je t'envoie un mail pour le reste ;-)

++
