### ISSUE TITLE
responsive

### ISSUE THREAD

**Issue by robbee** [twigy/twigy-web#14]
Hello 

Y a un truc qui marche plus :-( Le responsive sur mobile et tablette ne fonctionne plus... Je comprends pas trop.. Je déploie le front et le back sur heroku maintenant ... http://twigy.fr

Le responsive fonctionne sur PC ??

Bizarre !!

Merci

**Comment by alaumiere** [comment]
Hello,

Sur http://twigy-web.herokuapp.com c'est ok par contre.
En regardant le source de twigy.fr, on peut voir une inclusion de l'app déployée sur heroku via une frame (beurk!), c'est la cause probable du pb.
Il faudrait suivre le tuto https://devcenter.heroku.com/articles/custom-domains pour associer le NDD twigy.fr à l'app via un enregistrement CNAME plutôt que d'utiliser la frame de redirection d'ovh.

A+

**Comment by robbee** [comment]
Bien vu !! Merci je regarde le tuto asap

++

**Comment by robbee** [comment]
Ayé ! C'est ok sur twigy.fr et www.twigy.fr

Merci !!
