### ISSUE TITLE
UI Ajout d'images

### ISSUE THREAD

**Issue by alaumiere** [twigy/twigy-web#15]
@robbee Il faudrait ajouter les images manquantes pour le MVP, à savoir
- le logo wello black pour l'écran d'inscription
- les icônes activités en version couleur et gris foncé : icon-{{uid}}.png, icon-{{uid}}-grey.png

icon-jeux.png
icon-cuisine.png 
icon-coup_de_main.png 
icon-entretien.png
icon-service.png 
icon-bien_etre.png 
icon-vigilance.png
icon-verification.png
icon-leve_couche.png 
icon-jeux-grey.png 
icon-cuisine-grey.png
icon-coup_de_main-grey.png
icon-entretien-grey.png 
icon-service-grey.png 
icon-bien_etre-grey.png 
icon-vigilance-grey.png
icon-verification-grey.png
icon-leve_couche-grey.png

**Comment by robbee** [comment]
Ca devrait etre bon. Tell me

++

**Comment by alaumiere** [comment]
Merci! nickel!
