### ISSUE TITLE
Default description

### ISSUE THREAD

**Issue by robbee** [twigy/twigy-web#17]
Re salut

J'ai rajouté les descriptions par défaut. Je voudrais sauver la desc par defaut quand l'utilisateur ne la surcharge pas... j'y arrive pas completement (pb de binding)

Merci

**Comment by robbee** [comment]
Perfect ! Thanks ;-)

**Comment by robbee** [comment]
OK... Quand je clic sur une autre activité il faut reseter la description en cours.. 

Ex : 

- Je clic sur café (y a la desc correspondante)
- Je rentre un text
- Je clic sur vistie
- La description par defaut de visite vient écrasé ce que j'avais commencé à écrire

Merciiiii

**Comment by alaumiere** [comment]
Bien vu, idem pour la date, l'heure et la récurrence qui n'étaient pas reseter.
ça devrait être bon

**Comment by robbee** [comment]
Perfect !!! Merci !
