### ISSUE TITLE
date range from now to next week

### ISSUE THREAD

**Issue by robbee** [twigy/twigy-web#4]
Coucou

Je galere avec les dates .. je voudrais dans le twig controleur faire partir la liste de maintenant a dans une semaine... J'ai fais un truc mais ca n'a pas l'air très réglo ;-)

Merci

**Comment by alaumiere** [comment]
La manipulation de date avec l'objet Date natif est relativement limitée, j'ai ajouté l'exemple avec momentjs.
enjoy

**Comment by robbee** [comment]
t'es plus rapide que la lumiere !! Aurelien Lumiere !!

Merci canon



Alexandre
