### ISSUE TITLE
ng-switch with input

### ISSUE THREAD

**Issue by robbee** [twigy/twigy-web#6]
Salut Aurélien,

Je suis dans le modal.html. Je fais un ng-switch suivant le type. Dans mon switch je recupere la valeur de l'heure.. que je veux envoyer au controlleur via le boutton qui est a l’extérieur du switch. La valeur n'est pas passé... 

Un pb de scope j'ai l'impression... 

Merci beaucoup

**Comment by alaumiere** [comment]
Hello,
L'objet $scope.newTwig.hour ne peut pas être manipulé car $scope.newTwig n'est pas initialisé.
Pour obtenir le comportement souhaité, il faut juste initialiser cet objet dans le contrôleur NewTwigController.
Par exemple $scope.newTwig = {}; 
ou $scope.newTwig = { hour: "10"}; si l'on souhaite définir une valeur par défaut à la création
enjoy

**Comment by robbee** [comment]
Bah oui...
F*ck & merci
