### ISSUE TITLE
deploy

### ISSUE THREAD

**Issue by robbee** [twigy/twigy-web#7]
Hello ! Alors les oeufs de Paques ;-)

Je n'arrive plus a changer le port par default sur twigy.fr. Mettre le port 80 a la place du 3000... je sais plus ou c'est ?

Thanks

**Comment by alaumiere** [comment]
Hello !

Pour servir le dist, tu peux faire un  `node web.js` après avoir buildé l'app via un `gulp`

A+

**Comment by robbee** [comment]
rm -rf dist + refresh du navigateur 

Avec la gastro on est moins lucide (y a quand meme qq chose qui m'échappe.. on en discute a l'ocass)

Merci
