### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by robbee** [twigy/twigy-web#8]
Yo

Impossible d'ajouter du contenu après le jumbotron dans le main.html.. Il se positionne en dessous

Thanks

**Comment by alaumiere** [comment]
done!
Pense à paramétrer ton IDE/éditeur pour qu'il t'indique quand le code est invalide ;-)

**Comment by robbee** [comment]
Yo 

je pensais a un truc du style https://www.spotify.com/fr/ 

apres l'image il y a une zone balnche par exemple ou je peux coller un autre contenu

C'est tout con mais ca m'a gavé .. ;-) c'est pas urgent surtout !

thanks

**Comment by robbee** [comment]
Perfect !
