### ISSUE TITLE
Des p'tit truc ;-)

### ISSUE THREAD

**Issue by robbee** [twigy/twigy-web#9]
Salut Aurélien

Voici qq p'tit truc qui me pose pb.. ca devrait être un jeu d'enfant pour toi ;-)

- Question sur la home page : Quand je mets de opacity sur l'image, le texte par dessus est egalement en opacity.. j'ai cru voir sur gg que la façon la plus simple ct de faire les images en opacity directement ? Right ?
- Sur la page account create je voudrais que le bouton + Lien = la taille des input juste au dessus (aligné en gros)
- Sur la page account profile la drop box ne fonctionne pas et je voudrais aussi qu'elle fasse la taille des input
- Sur la vue timeline quand je réduit l'écran est-il possible que l'affichage de la date soit différente ? style aligné ?
- Pour les commentaires... je réfléchi encore... j'hésite entre les commentaire sur un twig et la vue consolidé (carnet de liaison...) Ce qui est sur c'est que j'arrive pas a faire le join avec les helper ;-)
- pour la création du compte (notament l'avatar) j'ai vu [ca](http://jsfiddle.net/alexk111/rw6q9/) .. ? T'en pense quoi ? (https://github.com/alexk111/ngImgCrop)

Sinon, j'ai vu tes modifs  ! Nickel !!

++

**Comment by alaumiere** [comment]
Salut,

- L'opacité s'applique sur le conteneur et ses enfants, avec aucun moyen facile de rétablir une opacity à 1 sur les enfants. Du coup soit faut décrocher les enfants du background comme dans la partie haute de la page, soit fournir directement les images avec la bonne opacity. Donc si on ne change pas les images régulièrement le plus rapide est de fournir les images avec le bon niveau de transparence.
- Je n'ai pas trop compris ce que tu souhaite sur account create, si c'est un lien de même taille que le bouton, il faut mettre une classe btn-lg
- Pour la "dropbox" profile, je pense que le besoin est d'afficher une combobox (un select évolué) et non un dropdown classique (bouton avec plusieurs actions). Même si visuellement la différence n'est pas grande, la sémantique et le composant derrière ne sont pas les mêmes. Il faudra intégrer angular-ui-select ... je m'en occupe.
- Est-ce que l'affichage de la date telle qu'elle est sur l'agenda (en affichage réduit) te conviendrais aussi pour l'affichage réduit de la timeline ?
- Les deux notions peuvent peut-être cohabiter amha. Le carnet de liaison concernerait les commentaires qui ne sont pas propre à un twig.
- Pour l'avatar ça me parait indispensable. ngImgCrop n'a plus l'air maintenu mais il y a en à d'autres (angular-image-crop, ngCropper) à tester.

+

**Comment by robbee** [comment]
Salut

- ok pour l'opacité.. je vais gerer le image directement
- je voulais que le bouton soit plus large.. (bouton + Lien = taille de l'input du dessus) bref c'est pas grave..
- Pour le combo : ok tu as raison.. c'est plus adapté .. j'avais zappé le combo.. :-(
- Pour la date je voudrais que "lundi 14 juillet" soit a l'horizontal plutot que empilé
- Commentaire.. oui je vois.. mais je pas qui ai d'ambiguïté ...
- OK pour l'avatar...

Allez a ++

**Comment by alaumiere** [comment]
Hello,

ça devrait être bon pour les boutons, la combo et la date. Je vais regarder pour l'avatar.
Nb: attention pour les images en bg, faut que le contraste du texte au dessus soit suffisant pour que ça reste lisible.

A+

**Comment by robbee** [comment]
Super !! je vais regarder !! Ok pour le bg.. je fais des essaies.. c'est
pas terrible pour l'instant.. je reconnais :-(

++

Alexandre
